import Joi from "joi";

export const IdSpec = Joi.alternatives().try(Joi.string(), Joi.object()).description("a valid ID");

// define the spec for userCredentials
export const UserCredentialsSpec = Joi.object()
.keys({
    email: Joi.string().email().example("homer@simpson.com").required(),
    password: Joi.string().example("secret").required(),
})
.label("UserCredentials");

// define the spec for User details
export const UserSpec = UserCredentialsSpec.keys({
  firstName: Joi.string().example("Homer").required(),
  lastName: Joi.string().example("Simpson").required(),
}).label("UserDetails");

// add the id's generated by the database to the user details above
export const UserSpecPlus = UserSpec.keys({
  _id: IdSpec,
  __v: Joi.number(),
}).label("UserDetailsPlus");

export const UserArray = Joi.array().items(UserSpecPlus).label("UserArray");

// define the spec for location object
export const LocationSpec = Joi.object()
  .keys( {
    location: Joi.string().required().example("Glengarriff"),
    latitude: Joi.number().required().example(51.75),
    longitude: Joi.number().required().example(9.55),
    date: Joi.string().optional().example("August 2022"),
    details: Joi.string().optional().example("Overcast, went to Garnish Island"),
    listid: IdSpec,
})
.label("Location");

// add the id's generated by the database to the location details above
export const LocationSpecPlus = LocationSpec.keys({
  _id: IdSpec,
  __v: Joi.number(),
}).label("LocationPlus");

export const LocationArraySpec = Joi.array().items(LocationSpecPlus).label("LocationArray");

// define the spec for the list object
export const ListSpec =  Joi.object()
  .keys({
    title: Joi.string().required().example("Cork"),
    userid: IdSpec,
    locations: LocationArraySpec,
  })
  .label("List");

  // add the id's generated by the database to the list details above
export const ListSpecPlus = ListSpec.keys({
    _id: IdSpec,
    __v: Joi.number(),
  }).label("ListPlus");
  
export const ListArraySpec = Joi.array().items(ListSpecPlus).label("ListArray");

// define the jwt authentication spec 
export const JwtAuth = Joi.object()
  .keys({
    success: Joi.boolean().example("true").required(),
    token: Joi.string().example("eyJhbGciOiJND.g5YmJisIjoiaGYwNTNjAOhE.gCWGmY5-YigQw0DCBo").required(),
  })
  .label("JwtAuth");
